#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          14
bspc config focused_border_color \#8FBCBB

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true
bspc config directional_focus_tightness low
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

sleep 1
autorandr -f -c
